language: python
sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy"  # PyPy2 2.5.0
  - "pypy-5.3.1"

install:
  - |
    if [[ $TRAVIS_PYTHON_VERSION != 'pypy-5.3.1' ]]; then
        pip install coverage
        pip install coveralls
    fi
  - pip install zope.interface
  - pip install zope.lifecycleevent
  - pip install zope.component
  - pip install zope.deprecation
  - pip install https://github.com/bluedynamics/odict/archive/master.zip
  - pip install https://github.com/bluedynamics/plumber/archive/master.zip
  - pip install https://github.com/bluedynamics/node/archive/master.zip
  - pip install -e .

script:
  - python -m node.ext.ugm.tests.__init__
  - |
    if [[ $TRAVIS_PYTHON_VERSION != 'pypy-5.3.1' ]]; then
        coverage run --source src/node/ext/ugm -m node.ext.ugm.tests.__init__
        coverage report
    fi

after_success:
  - |
    if [[ $TRAVIS_PYTHON_VERSION != 'pypy-5.3.1' ]]; then
        coveralls
    fi
