language: python
sudo: false

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"  # PyPy2 2.5.0
  - "pypy-5.3.1"

install:
  - pip install coverage
  - pip install coveralls
  - pip install zope.interface
  - pip install zope.lifecycleevent
  - pip install zope.component
  - pip install zope.deprecation
  - pip install https://github.com/bluedynamics/odict/archive/master.zip
  - pip install https://github.com/bluedynamics/plumber/archive/master.zip
  - pip install https://github.com/bluedynamics/node/archive/master.zip
  - pip install -e .

script:
  - python -m node.ext.ugm.tests.__init__
  - coverage run --source src/node/ext/ugm -m node.ext.ugm.tests.__init__
  - coverage report

after_success:
  - coveralls
